// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI2Zn6MBd-rtj6dmFJ8oZdxvbrqv6nllk',
    appId: '1:519103232524:web:d2bd1354a633a906d6cc29',
    messagingSenderId: '519103232524',
    projectId: 'e-commerce-app-c26fe',
    authDomain: 'e-commerce-app-c26fe.firebaseapp.com',
    storageBucket: 'e-commerce-app-c26fe.firebasestorage.app',
    measurementId: 'G-HVJ3J3DW37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSqXRWWcKd9oZJ-lT86Lsyu78SPDbo9fE',
    appId: '1:519103232524:android:e9b6809a772775a3d6cc29',
    messagingSenderId: '519103232524',
    projectId: 'e-commerce-app-c26fe',
    storageBucket: 'e-commerce-app-c26fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ElbsnYhSLnxAvEzcE4zr9kjhRMmkJqE',
    appId: '1:519103232524:ios:3259da573eee8106d6cc29',
    messagingSenderId: '519103232524',
    projectId: 'e-commerce-app-c26fe',
    storageBucket: 'e-commerce-app-c26fe.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ElbsnYhSLnxAvEzcE4zr9kjhRMmkJqE',
    appId: '1:519103232524:ios:3259da573eee8106d6cc29',
    messagingSenderId: '519103232524',
    projectId: 'e-commerce-app-c26fe',
    storageBucket: 'e-commerce-app-c26fe.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI2Zn6MBd-rtj6dmFJ8oZdxvbrqv6nllk',
    appId: '1:519103232524:web:5b53052b776e33b6d6cc29',
    messagingSenderId: '519103232524',
    projectId: 'e-commerce-app-c26fe',
    authDomain: 'e-commerce-app-c26fe.firebaseapp.com',
    storageBucket: 'e-commerce-app-c26fe.firebasestorage.app',
    measurementId: 'G-VZBKMHZE7K',
  );
}
